# Generated by Django 5.2.7 on 2025-12-03 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_attendance_time'),
        ('accounts', '0004_alter_customuser_role_alter_parentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectoffering',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='accounts.teacherprofile'),
        ),
    ]
