# Generated by Django 5.2.7 on 2025-12-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_subjectoffering_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectoffering',
            name='section',
            field=models.CharField(default='a', max_length=20),
        ),
    ]
