# Generated by Django 5.2.7 on 2025-12-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subjectoffering_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectoffering',
            name='section',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=20),
        ),
    ]
