# Generated by Django 5.2.7 on 2025-12-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_subjectoffering_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('subject', 'school_year', 'year', 'section')},
        ),
    ]
