# Generated by Django 5.2.7 on 2025-12-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_subjectoffering_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectoffering',
            old_name='year',
            new_name='year_level',
        ),
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('subject', 'school_year', 'year_level', 'section')},
        ),
    ]
