# Generated by Django 5.2.7 on 2025-12-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_rename_year_subjectoffering_year_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectoffering',
            old_name='year_level',
            new_name='year',
        ),
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('subject', 'school_year', 'year')},
        ),
        migrations.RemoveField(
            model_name='subjectoffering',
            name='section',
        ),
    ]
