# Generated by Django 5.2.7 on 2025-12-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_rename_year_level_subjectoffering_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='year_level',
            field=models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')], default='1st', max_length=10),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='section',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_code', 'semester_number', 'year_level')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('subject', 'year', 'section', 'school_year')},
        ),
    ]
